name: Build Dashboard (Release)
on:
  push:
    tags:
      - v*

jobs:
  build-validation:
    name: Validate Code
    uses: ./.github/workflows/build-dash-validation.yaml
  build:
    name: Build and Upload
    uses: ./.github/workflows/build-dash-build-and-upload.yaml
    needs:
      - build-validation
    permissions:
      contents: 'read'
      id-token: 'write'
    with:
      CI_BUILD_TAG: ${{github.ref_name}}
